baseURL = "https://caliviptours.com/"
languageCode = 'en-us'
title = "Cali VIP Tours - Colombia - It is all about the experience"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Cali VIP Tours"
    weight = 1
    contentDir = "content/en"
  [languages.es]
    title = "Cali VIP Tours en Espa√±ol"
    weight = 2
    contentDir = "content/es"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "calivip"
  favicon = "/icons/favicon.ico"
  site_logo = "/logos/logo.jpg"
  description = "Cali VIP Tours Colombia - It's all about the experience"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 6

[[params.ananke_socials]]
name = "Instagram"
url = "https://instagram.com/caliviptours"

[[params.ananke_socials]]
name = "Twitter"
url = "https://twitter.com/caliviptours"

[[params.ananke_socials]]
name = "Facebook"
url = "https://www.facebook.com/profile.php?id=61550541183437&mibextid=ZbWKwL"

